// Phase 4 parity vector verification.
//
// Blind-index vectors: byte-EXACT (Argon2id is deterministic). Each entry in blind-index.json was
// generated by the authoritative Go SDK (harness/vectors/gen_go.go). This test asserts that the TS
// WASM SDK (blindIndexString) produces the same base64url-unpadded value for the same raw email
// input — proving cross-language parity byte-for-byte.
//
// Vault vectors: Open-parity ONLY. The envelopeHex values were sealed by the Go SDK; this test
// asserts that the TS SDK can open them and recover the exact plaintextHex. Encrypt is
// non-deterministic (random nonce + DEK each run), so byte-exact envelope equality is neither
// expected nor tested here — only the Open direction matters for interop.
//
// These vectors are also validated at generation time by harness/vectors/gen_go.go (round-trip
// assertion) and by the existing vault-parity.test.ts (live Go↔TS round-trip).

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, it, expect, beforeAll } from 'vitest';
import { init } from '../src/wasm';
import { blindIndexString } from '../src/blindIndex';
import { importVaultKey, open } from '../src/vault';

const here = dirname(fileURLToPath(import.meta.url));
// test/ → packages/tessera-ts → packages → tessera-ts → (sibling) ciphera-tessera/conformance/vectors.
// Same relative layout locally (under Tessera/) and in CI (sibling checkouts under the workspace root).
const VECTORS_DIR = join(here, '..', '..', '..', '..', 'ciphera-tessera', 'conformance', 'vectors');

// ── Helpers ─────────────────────────────────────────────────────────────────

const fromHex = (h: string): Uint8Array => new Uint8Array(Buffer.from(h, 'hex'));

// ── Load vector files ────────────────────────────────────────────────────────

interface BlindIndexVector {
  email: string;
  blindIndexBase64Url: string;
}

interface VaultVector {
  vaultKeyHex: string;
  context: string;
  plaintextHex: string;
  envelopeHex: string;
}

// The canonical vector files carry a versioned header object; the vectors live under `.vectors`.
const biVectors: BlindIndexVector[] = JSON.parse(
  readFileSync(join(VECTORS_DIR, 'blind-index.json'), 'utf8'),
).vectors;
const vaultVectors: VaultVector[] = JSON.parse(
  readFileSync(join(VECTORS_DIR, 'vault.json'), 'utf8'),
).vectors;

// ── Blind-index: byte-exact cross-language parity ────────────────────────────

beforeAll(async () => {
  // Must be awaited before any WASM-backed API (blindIndexString calls blindIndexBytes internally).
  await init();
}, 10_000);

describe('blind-index parity vectors (TS WASM byte-exact == Go-generated)', () => {
  for (const { email, blindIndexBase64Url } of biVectors) {
    it(
      `matches Go for email: "${email}"`,
      () => {
        // blindIndexString normalizes (trim → lower) inside the WASM core, matching Go's NormalizeEmail.
        expect(blindIndexString(email)).toBe(blindIndexBase64Url);
      },
      60_000, // Argon2id(64 MiB) per call — may be slow on CI
    );
  }
});

// ── Vault: Go-sealed envelopes open correctly in TS ──────────────────────────

describe('vault parity vectors (TS opens Go-sealed envelopes)', () => {
  for (const { vaultKeyHex, context, plaintextHex, envelopeHex } of vaultVectors) {
    it(
      `opens Go envelope for context="${context}" plaintext="${Buffer.from(plaintextHex, 'hex').toString('utf8')}"`,
      async () => {
        const vaultKey = await importVaultKey(fromHex(vaultKeyHex));
        const pt = await open(vaultKey, context, fromHex(envelopeHex));
        // Assert byte-exact recovery of plaintext.
        expect(Buffer.from(pt).toString('hex')).toBe(plaintextHex);
      },
      10_000,
    );
  }
});
